version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www

  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"

  webserver-frontend:
    build:
      context: ./frontend
      dockerfile: ./../docker/nginx-frontend.Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80"

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1